const focusedCategoryPage = ({ category, title, metaTitle, metaDescription, keywords, intro, selection, branding, uses, relatedLinks, faqs }) => ({
  category,
  title,
  metaTitle,
  metaDescription,
  keywords,
  intro,
  sections: [
    {
      heading: 'Choose the right product and specification',
      paragraphs: [selection],
      items: uses,
    },
    {
      heading: 'Logo branding and artwork approval',
      paragraphs: [branding],
    },
    {
      heading: 'Information to send for a bulk quotation',
      paragraphs: ['Share the product or style, approximate quantity, required sizes or format, branding artwork, delivery city and needed date. CoachingPromo can then confirm current availability, suitable customization, pricing and the expected production schedule before you approve the order.'],
    },
  ],
  relatedLinks,
  faqs,
});

export const subcategorySeoContent = {
  'hoodies-jackets': {
    category: 'apparel-accessories',
    title: 'Custom Hoodies for Coaching Institutes & Colleges in India',
    metaTitle: 'Custom Hoodies for Coaching Institutes | Bulk India',
    metaDescription: 'Order custom hoodies and winter jackets in bulk for coaching institutes, schools and colleges in India, with logo printing, embroidery and Pan-India delivery.',
    categoryMetaTitle: 'Bulk Custom Hoodies & Jackets India | Logo Printing',
    categoryMetaDescription: 'Browse pullover, zipper and fleece hoodies and winter jackets in bulk with custom logo printing or embroidery for institutes across India.',
    keywords: [
      'custom hoodies for coaching institutes',
      'custom hoodies with logo in bulk India',
      'bulk hoodie printing India',
      'coaching institute winter jackets',
      'custom college hoodies India',
      'custom hoodies for students',
      'school winter jackets manufacturer India',
      'customized winter uniforms for schools',
      'college hoodies bulk order',
      'custom winter wear for educational institutes',
      'embroidered hoodies for institutes',
      'logo printed jackets in bulk',
      'fleece hoodies with logo printing',
      'staff winter jackets with logo',
      'custom zipper hoodies bulk India',
      'premium 300 GSM hoodies with institute logo',
      'personalized hoodies for student batches',
      'custom hoodies for college societies',
      'bulk jackets for schools and colleges',
      'custom sweatshirts for coaching institutes',
      'institute logo embroidery on hoodies',
      'custom hoodies for teachers and faculty',
      'bulk pullover hoodies for students',
      'custom varsity jackets for colleges',
      'coaching centre uniform supplier India',
      'branded winter wear with Pan-India delivery',
      'custom hoodie manufacturer India',
      'high GSM hoodies bulk India',
      'college fest hoodies with logo',
      'student batch hoodies India',
      'school staff winter uniforms',
      'DTF hoodie printing India',
    ],
    intro: [
      'Custom hoodies for coaching institutes give student batches, faculty and centre staff practical winter wear with a consistent institute identity. CoachingPromo supplies bulk pullover hoodies, zipper hoodies, sweatshirts and jackets with your logo, colours, batch name or campaign artwork for delivery across India.',
      'Whether you are planning coaching centre uniforms, college society merchandise, school winter jackets or event apparel, the order can be configured around garment style, fabric weight, branding method, size mix and quantity. Share your requirement to receive a suitable product recommendation and bulk quotation.',
    ],
    sections: [
      {
        heading: 'Pullover, zipper and winter jacket options',
        paragraphs: [
          'Choose a style for the way your students or team will use it. Pullover hoodies suit student batches, college clubs and promotional merchandise, while full-zip hoodies are convenient for staff uniforms and daily layering. Winter jackets and varsity-inspired styles are suitable for faculty, college societies, sports groups and institutional events.',
        ],
        items: [
          'Bulk pullover hoodies for students and batches',
          'Custom zipper hoodies for staff and faculty',
          'Logo-printed or embroidered sweatshirts',
          'College society, fest and varsity-style jackets',
          'School and coaching centre winter uniforms',
        ],
      },
      {
        heading: 'Fabric weight, warmth and sizing',
        paragraphs: [
          'Fabric and GSM should match the climate, intended use and budget. Mid-weight fleece works well for everyday institute wear, while premium 300 GSM and heavier options provide a warmer, more structured finish. Ask about available cotton-rich, blended and fleece fabrics, colour choices and inclusive size runs before confirming production.',
          'For a reliable bulk fit, provide the expected student or staff size split and request the current garment measurement chart. A sample or approved size reference can help institutions confirm the fit before a larger order.',
        ],
      },
      {
        heading: 'Institute logo printing and embroidery',
        paragraphs: [
          'Your artwork, placement, colour count and garment fabric determine the most suitable branding method. Embroidery gives institute crests and chest logos a durable, premium appearance. Screen printing is efficient for larger quantities and bold artwork, while DTF or heat-transfer printing can reproduce detailed, multi-colour batch and event designs.',
        ],
        items: [
          'Institute crest or logo on the front chest',
          'Large back print with institute, course or batch name',
          'Sleeve, name, number or department personalization',
          'Brand-colour garments and coordinated print threads or inks',
          'Artwork review before bulk hoodie printing',
        ],
      },
      {
        heading: 'Hoodies for students, teachers and college groups',
        paragraphs: [
          'Custom winter wear can support a range of education-sector needs: coaching institute staff uniforms, student batch hoodies, teacher and faculty jackets, college society merchandise, fest teams, sports groups, alumni meets and admission campaigns. One coordinated design helps people identify the institution while giving recipients something useful beyond a single event.',
        ],
      },
      {
        heading: 'How to plan a bulk hoodie order',
        paragraphs: [
          'Send your approximate quantity, preferred hoodie or jacket style, required delivery city, size split, garment colour and logo file. Also mention the expected use and delivery date. These details help the team recommend an appropriate fabric, branding process and production plan instead of quoting an unsuitable one-size-fits-all specification.',
          'Bulk pricing depends on quantity, garment construction, GSM, number of print or embroidery locations, personalization and delivery requirements. CoachingPromo confirms the specification and quotation for approval before production and arranges dispatch to institutes across India.',
        ],
      },
    ],
    relatedLinks: [
      { href: '/custom-hoodies-for-coaching-institutes', label: 'Custom hoodies for coaching institutes' },
      { href: '/apparel-accessories/uniform-jackets', label: 'Explore custom uniform jackets' },
      { href: '/apparel-accessories/polo-t-shirts', label: 'Explore embroidered polo T-shirts' },
      { href: '/contact', label: 'Request a bulk winter-wear quote' },
    ],
    faqs: [
      {
        q: 'Can coaching institutes order custom hoodies with their logo in bulk?',
        a: 'Yes. Coaching institutes can order hoodies in bulk with a chest logo, back print, sleeve branding, batch name or other approved artwork. Available garment and branding options are confirmed with the quotation.',
      },
      {
        q: 'Which hoodie styles are suitable for students and staff?',
        a: 'Pullover hoodies are popular for student batches, societies and event merchandise. Zipper hoodies and winter jackets are convenient for staff, faculty and daily uniform use. The best choice depends on climate, dress code and budget.',
      },
      {
        q: 'Is embroidery or printing better for an institute logo?',
        a: 'Embroidery suits compact crests and chest logos that need a premium finish. Screen printing works well for bold designs and larger quantities, while DTF or heat transfer can suit detailed multi-colour artwork. The garment fabric and design determine the best method.',
      },
      {
        q: 'Are 300 GSM fleece hoodies available for institute orders?',
        a: 'Premium 300 GSM and other fabric-weight options may be selected according to the required warmth, finish and current garment availability. Confirm the exact fabric composition, GSM, colour and size chart in your quotation.',
      },
      {
        q: 'Can we order personalized hoodies for a student batch or college society?',
        a: 'Yes. Subject to the selected production method, hoodies can include a batch year, society name, department, event artwork, individual name or number in addition to the institute logo.',
      },
      {
        q: 'What information is needed for a bulk hoodie quotation?',
        a: 'Share the approximate quantity, style, colour, size split, logo or artwork, branding positions, delivery city and required date. This allows the team to recommend the right garment and calculate an accurate quote.',
      },
      {
        q: 'Do you deliver custom hoodies and winter jackets across India?',
        a: 'Yes. CoachingPromo arranges Pan-India delivery for institutional hoodie and jacket orders. The dispatch plan and delivery estimate are confirmed after the product specification, quantity and destination are finalized.',
      },
    ],
  },
  'uniform-jackets': focusedCategoryPage({
    category: 'apparel-accessories',
    title: 'Teacher Jackets and Staff Winter Uniforms with Logo',
    metaTitle: 'Teacher Jackets with Logo | Bulk Institute Uniforms',
    metaDescription: 'Order teacher jackets and staff winter uniforms with institute logo branding. Compare jacket styles and request bulk pricing for delivery in India.',
    keywords: ['teacher jacket', 'jackets for teachers', 'teacher jackets', 'staff winter jackets with logo', 'coaching institute winter jackets', 'school winter jackets India'],
    intro: [
      'Teacher jackets help coaching centres, schools and colleges create a consistent winter uniform for faculty, counsellors, reception teams and support staff. Choose a jacket according to daily use, local weather, dress code and the placement required for your institute logo.',
      'The same page can also support student coordinators, event teams and multi-centre institute staff. Confirm the current fabric, lining, colour and size chart for the selected item before deciding the final size mix.',
    ],
    selection: 'Compare lightweight uniform jackets for everyday layering with warmer options for colder regions. Check closure type, pockets, collar or hood style, fabric composition and garment measurements rather than selecting on appearance alone.',
    branding: 'Compact embroidered crests can suit a formal staff look, while printing may suit larger back artwork or event branding. The best process depends on the jacket fabric and artwork detail, so provide a clear logo file and intended placement for review.',
    uses: ['Faculty and teacher winter uniforms', 'Coaching-centre reception and counselling teams', 'School staff, coordinators and event crews', 'Multi-branch institute apparel'],
    relatedLinks: [{ href: '/apparel-accessories/hoodies-jackets', label: 'Student hoodies and winter wear' }, { href: '/apparel-accessories/polo-t-shirts', label: 'Staff polo T-shirts' }, { href: '/contact', label: 'Request a uniform-jacket quote' }],
    faqs: [
      { q: 'Can teacher jackets carry an institute logo?', a: 'Yes, suitable jackets can be branded with an institute name or logo. Embroidery or printing is selected according to the fabric, artwork and required placement.' },
      { q: 'How should a school or coaching centre plan jacket sizes?', a: 'Collect the wearer size split and compare it with the current garment measurement chart. For larger orders, ask which approval or sample options are available before final production.' },
      { q: 'Are uniform jackets available for faculty and support staff?', a: 'The collection can be used for teachers, faculty, counsellors, reception teams, coordinators and other staff. Available colours and styles are confirmed during quotation.' },
      { q: 'What details are needed for a teacher-jacket quote?', a: 'Share style, quantity, size split, logo, branding position, delivery city and required date.' },
    ],
  }),
  'polo-t-shirts': focusedCategoryPage({
    category: 'apparel-accessories',
    title: 'Custom Polo T-Shirts for Coaching Classes and Staff',
    metaTitle: 'Coaching Institute Polo T-Shirts | Bulk Logo Printing',
    metaDescription: 'Custom polo T-shirts for coaching classes, institute staff and student teams. Compare fabric and logo options and request a bulk quote in India.',
    keywords: ['t shirt for coaching classes', 't shirt for coaching institute', 'coaching classes t shirt design', 'custom polo t-shirts for institutes', 'coaching staff uniform t-shirts'],
    intro: ['Custom polo T-shirts give coaching faculty, admissions teams and event staff a coordinated uniform while keeping the institute name visible. They can also be planned for student representatives, seminars, workshops and outreach teams.', 'Select a polo by intended wear, climate, fabric feel, collar construction, colour and size range. Product details differ, so use the current listing and measurement information when preparing a bulk order.'],
    selection: 'Cotton-rich options can suit everyday comfort, while performance blends may be useful for active teams and outdoor events. Compare fabric composition, weight, fit and care requirements for the shortlisted product.',
    branding: 'A compact chest logo is a common uniform treatment. Sleeve, back or name branding may also be possible depending on the garment and artwork. Embroidery, screen printing and transfer methods each suit different designs and quantities.',
    uses: ['Teacher and coaching staff uniforms', 'Admissions and counselling teams', 'Seminars, workshops and institute events', 'Student volunteers and sports groups'],
    relatedLinks: [{ href: '/apparel-accessories/round-neck-t-shirts', label: 'Round-neck event T-shirts' }, { href: '/apparel-accessories/uniform-jackets', label: 'Teacher winter jackets' }, { href: '/contact', label: 'Request a coaching T-shirt quote' }],
    faqs: [
      { q: 'Can coaching classes order polo T-shirts with their logo?', a: 'Yes. Share the logo, quantity and preferred placement so the suitable branding method can be confirmed for the selected polo.' },
      { q: 'Are polo T-shirts suitable for teachers and institute staff?', a: 'Polo T-shirts are commonly considered for faculty, counselling, reception, admissions and event teams because they balance a uniform appearance with everyday wear.' },
      { q: 'Which details affect bulk polo T-shirt pricing?', a: 'Garment style, fabric, quantity, size mix, number of branding positions, artwork and delivery requirements affect the quotation.' },
      { q: 'Can names or departments be added?', a: 'Personalized names, roles or departments may be possible for selected garments and processes. Include the personalization list when requesting a quote.' },
    ],
  }),
  'round-neck-t-shirts': focusedCategoryPage({
    category: 'apparel-accessories',
    title: 'Printed Coaching T-Shirts for Students and Events',
    metaTitle: 'Coaching Class T-Shirt Printing | Bulk Student Tees',
    metaDescription: 'Printed T-shirts for coaching classes, student batches, education events and campaigns. Plan fabric, sizes and logo printing for a bulk order.',
    keywords: ['t-shirt for coaching classes', 'coaching classes t shirt design', 'printed t-shirts for students', 'bulk coaching institute t-shirts', 'student batch t-shirts'],
    intro: ['Round-neck T-shirts are a flexible option for student batches, institute campaigns, orientation programmes, competitions and event volunteers. A clear design brief helps match the garment colour and print treatment to the institute identity.', 'Use the page to compare available products, then confirm fabric, size chart, artwork dimensions and quantity before production.'],
    selection: 'Consider how long the T-shirt will be worn, expected weather, preferred fit and whether it is for daily use or a single event. Confirm the selected product specification rather than assuming every round-neck T-shirt uses the same fabric or GSM.',
    branding: 'Front-chest logos, large back designs and batch artwork can require different print processes. Provide vector artwork where possible and specify the garment colour so contrast and print feasibility can be checked.',
    uses: ['Student batches and achiever groups', 'Orientation and admission campaigns', 'Workshops, competitions and education fairs', 'Institute sports and volunteer teams'],
    relatedLinks: [{ href: '/apparel-accessories/polo-t-shirts', label: 'Institute polo T-shirts' }, { href: '/bags/tote-bag', label: 'Student-kit tote bags' }, { href: '/contact', label: 'Discuss a printed T-shirt order' }],
    faqs: [
      { q: 'Can a batch name be printed on coaching-class T-shirts?', a: 'Yes, batch, course or event artwork may be printed when it is suitable for the selected garment and production method.' },
      { q: 'What file should be sent for T-shirt printing?', a: 'A vector logo or high-resolution artwork is preferred. Include colour references, print position and approximate dimensions.' },
      { q: 'How is the correct size mix planned?', a: 'Collect wearer requirements against the current measurement chart and provide the final quantity for each size.' },
      { q: 'Can the same design be used on polos and round-neck T-shirts?', a: 'Often yes, but the artwork size or branding process may need adjustment for the fabric and garment construction.' },
    ],
  }),
  'tote-bag': focusedCategoryPage({
    category: 'bags',
    title: 'Custom Tote Bags for Coaching Institutes and Student Kits',
    metaTitle: 'Custom Tote Bags for Coaching Institutes | Bulk India',
    metaDescription: 'Printed tote bags for coaching institutes, college events and student kits. Compare materials, sizes and logo options for a bulk order in India.',
    keywords: ['tote bag for coaching', 'custom tote bags for coaching institutes', 'student kit tote bags India', 'printed tote bags for institutes', 'bulk canvas tote bags for colleges'],
    intro: ['Custom tote bags can hold prospectuses, notebooks, welcome-kit items and event material while carrying a clear institute identity. They are relevant for admissions, seminars, orientation programmes, college societies and education fairs.', 'Choose the bag around what it needs to carry. Dimensions, handle length, material weight and closure affect everyday usefulness as much as the printed design.'],
    selection: 'List the intended contents and approximate weight before choosing a tote. Confirm bag dimensions, handle style, material, gusset and closure from the current product specification.',
    branding: 'Simple one- or two-colour logos can work well on many fabric bags, while detailed artwork may need another process. Print area and colour reproduction depend on the tote material and base colour.',
    uses: ['Student admission and welcome kits', 'Seminar and workshop material', 'College society and fest merchandise', 'Prospectus and counselling packs'],
    relatedLinks: [{ href: '/bags/institute-backpacks', label: 'Institute backpacks' }, { href: '/stationery/notebook', label: 'Custom notebooks' }, { href: '/contact', label: 'Request a tote-bag quote' }],
    faqs: [
      { q: 'What can an institute put in a tote-bag kit?', a: 'Common combinations include a prospectus, notebook, pen, ID material and event information. Check the bag dimensions and load suitability for the planned contents.' },
      { q: 'Can coaching-centre logos be printed on tote bags?', a: 'Yes, suitable bags can be printed with an institute logo or event design. The material and artwork determine the available process and print area.' },
      { q: 'Are canvas and other tote materials available?', a: 'Material choices depend on current products and stock. Confirm the composition, colour and construction in the quotation.' },
      { q: 'What information is needed for tote-bag pricing?', a: 'Share material or product preference, bag size, quantity, logo, print colours, delivery city and required date.' },
    ],
  }),
  'diary-set': focusedCategoryPage({
    category: 'promotional-items',
    title: 'Custom Coaching Diaries and Branded Diary Sets',
    metaTitle: 'Custom Coaching Diaries & Logo Diary Sets in Bulk',
    metaDescription: 'Order custom coaching diaries and branded diary sets for teachers, students and institute gifting. Compare formats and request bulk pricing.',
    keywords: ['coaching diary', 'custom diaries for coaching institutes', 'branded diary sets in bulk', 'teacher diary with institute logo', 'student academic diary printing'],
    intro: ['A branded diary can support faculty planning, student schedules, counselling notes, new-year gifting and institute welcome kits. Diary sets may pair a writing format with a pen or presentation pack, subject to the selected product.', 'Decide first whether the requirement is an academic diary, dated planner, undated notebook-style diary or gift set. Confirm the current year, page format and inclusions before approving artwork.'],
    selection: 'Check finished size, dated or undated layout, binding, cover material, page count and any included accessories. Seasonal diary orders benefit from early planning because dated formats and cover stocks can change.',
    branding: 'Cover printing, embossing or other treatments may be possible depending on the material. A small logo, institute name and restrained colour treatment can keep staff and faculty diaries easy to use.',
    uses: ['Teacher and faculty planning', 'Student academic schedules', 'New-year and staff gifting', 'Admissions and welcome kits'],
    relatedLinks: [{ href: '/stationery/notebook', label: 'Custom institute notebooks' }, { href: '/promotional-items/planner', label: 'Branded planners' }, { href: '/contact', label: 'Request diary-set pricing' }],
    faqs: [
      { q: 'Can an institute logo be added to a diary cover?', a: 'Yes, suitable covers can carry a printed, embossed or otherwise branded logo. The available method depends on the selected material.' },
      { q: 'Are dated and undated coaching diaries available?', a: 'Formats vary by product and season. Confirm whether the shortlisted diary is dated, undated or an academic planner before ordering.' },
      { q: 'Can diaries be included in a teacher or student kit?', a: 'Yes. Share the complete kit list and packing requirement so product compatibility can be reviewed.' },
      { q: 'When should a dated diary order be planned?', a: 'Plan early enough to confirm the correct year, stock, artwork and delivery schedule, especially for new-year distribution.' },
    ],
  }),
  'graduation-degree-folders': focusedCategoryPage({
    category: 'stationery',
    title: 'Custom Degree Certificate Folders for Convocation',
    metaTitle: 'Custom Degree Folders for Convocation | Bulk India',
    metaDescription: 'Custom degree certificate folders for colleges, universities and convocations. Compare A4 fit, cover options and logo branding for bulk orders.',
    keywords: ['degree folder', 'custom degree certificate folders India', 'convocation degree folders bulk', 'graduation certificate holder', 'college diploma folder with logo'],
    intro: ['Degree folders protect and present certificates during convocations, graduations and award ceremonies. Colleges and universities can coordinate the folder colour, cover artwork and certificate holding method with the event identity.', 'The most important check is fit: confirm the final certificate dimensions, orientation and insertion method before the folder specification is approved.'],
    selection: 'Confirm certificate size, portrait or landscape orientation, folder opening direction, internal pockets or corner holders, cover material and spine allowance. An actual certificate template can reduce fit errors.',
    branding: 'Institute crests, names and convocation details may be applied to suitable covers through printing, foil, embossing or another process. Feasibility depends on cover material and artwork detail.',
    uses: ['University and college convocations', 'Course-completion ceremonies', 'Academic awards and certifications', 'Alumni and institutional presentations'],
    relatedLinks: [{ href: '/apparel-accessories/graduation-stole', label: 'Custom graduation stoles' }, { href: '/apparel-accessories/graduation-gown', label: 'Graduation gowns' }, { href: '/contact', label: 'Request a degree-folder quote' }],
    faqs: [
      { q: 'What certificate size should a degree folder hold?', a: 'Many institutions use A4, but certificate sizes and orientation vary. Provide the exact finished dimensions before the folder is specified.' },
      { q: 'Can a college logo be added to a degree folder?', a: 'Yes, suitable covers can carry an institute crest, name or ceremony artwork. The finish is selected after reviewing the cover material and design.' },
      { q: 'What should be checked before a bulk convocation order?', a: 'Confirm certificate fit, orientation, holder style, cover colour, artwork, quantity, packing, venue city and event date.' },
      { q: 'Can degree folders coordinate with graduation stoles and gowns?', a: 'They can share institution colours and ceremony artwork. Review each product specification separately before confirming the complete set.' },
    ],
  }),
  'attendance-registers': focusedCategoryPage({
    category: 'stationery',
    title: 'Customized Attendance Registers for Schools and Institutes',
    metaTitle: 'Custom Attendance Registers for Schools & Coaching',
    metaDescription: 'Customized attendance registers with school or coaching-institute branding. Plan page format, binding and bulk printing for academic use.',
    keywords: ['custom attendance registers', 'school attendance register printing', 'coaching institute attendance register', 'personalized attendance registers', 'bulk academic registers'],
    intro: ['A customized attendance register can align routine academic records with an institute’s required class, batch or staff format. Before printing, define who will use the register and which fields need to appear on each page.', 'The page layout matters more than decorative branding. Review columns, date range, page count and writing space with the academic or administration team before approval.'],
    selection: 'Specify student or staff use, class or batch fields, daily or period-wise layout, page size, number of pages, binding and cover durability. Supply a sample layout if the institute follows an existing format.',
    branding: 'The cover can include the institute name, logo, branch, academic session and register type. Interior customization may be possible where the quantity and printing method support it.',
    uses: ['Student and classroom attendance', 'Coaching batch records', 'Faculty and staff attendance', 'Branch-wise academic administration'],
    relatedLinks: [{ href: '/stationery/notebook', label: 'Institute notebooks' }, { href: '/stationery/exam-pad', label: 'Customized exam pads' }, { href: '/contact', label: 'Discuss a register layout' }],
    faqs: [
      { q: 'Can the inside pages of an attendance register be customized?', a: 'Interior formats may be customized depending on quantity and production method. Share the required columns or an existing sample for review.' },
      { q: 'Can the academic session and branch name be printed?', a: 'Yes, these details can be included in the approved cover or page artwork where the selected specification supports it.' },
      { q: 'What should a school provide for a quotation?', a: 'Share register size, page count, layout, binding, cover requirement, quantity, delivery city and required date.' },
      { q: 'Are registers suitable for coaching batches as well as schools?', a: 'Yes. The layout can be planned around class, course, batch, subject or staff attendance requirements.' },
    ],
  }),
  'notebook': focusedCategoryPage({
    category: 'stationery',
    title: 'Custom Notebooks for Coaching Institutes and Students',
    metaTitle: 'Custom Notebooks for Coaching Institutes | Bulk Printing',
    metaDescription: 'Custom printed notebooks for coaching institutes, schools and student kits. Compare sizes, binding and cover branding for bulk orders.',
    keywords: ['custom notebooks for coaching institutes', 'branding notebooks for students', 'notebook printing India', 'bulk notebooks supplier', 'student study notebooks'],
    intro: ['Custom notebooks are useful for student kits, classroom notes, workshop material, faculty meetings and admission campaigns. A practical specification starts with the intended subject use and writing format, then adds institute branding to the cover.', 'Confirm notebook dimensions, page count, ruling, paper and binding for the selected option. If inside pages need institute information, share that requirement at the quotation stage.'],
    selection: 'Choose size, page count, ruled or unruled format, binding and cover construction according to daily use. A student workbook, event notebook and faculty notebook may need different specifications.',
    branding: 'Cover artwork can include the institute logo, course, batch or campaign identity. Detailed cover designs and customized inside pages require print-ready artwork and production review.',
    uses: ['Student welcome and study kits', 'Classroom and workshop notes', 'Faculty meetings and training', 'Admissions and seminar giveaways'],
    relatedLinks: [{ href: '/promotional-items/diary-set', label: 'Coaching diaries and gift sets' }, { href: '/bags/tote-bag', label: 'Tote bags for student kits' }, { href: '/contact', label: 'Request notebook pricing' }],
    faqs: [
      { q: 'Can notebook covers include an institute logo and batch name?', a: 'Yes, suitable notebook covers can carry approved institute, course, batch or event artwork.' },
      { q: 'Can the inside pages also be customized?', a: 'Custom inside pages may be possible depending on the specification and quantity. Share the required layout for review.' },
      { q: 'Which notebook details affect pricing?', a: 'Size, paper, page count, ruling, binding, cover, artwork, quantity and packing all influence the quotation.' },
      { q: 'Can notebooks and tote bags be supplied for one student kit?', a: 'They can be planned together. Share the complete item list and packing requirement so sizes and timelines can be coordinated.' },
    ],
  }),
  'graduation-stole': focusedCategoryPage({
    category: 'apparel-accessories',
    title: 'Customized Graduation Stoles for Colleges and Institutes',
    metaTitle: 'Customized Graduation Stoles | College Convocation',
    metaDescription: 'Custom graduation stoles for college, university and institute ceremonies. Plan colours, logo, course details and bulk requirements.',
    keywords: ['customized stole for graduation', 'graduation stole custom', 'custom stole', 'college convocation stoles', 'graduation sash with logo'],
    intro: ['Customized graduation stoles can identify the institution, course, graduating year or academic group during a ceremony. They can be coordinated with gowns, degree folders and the event colour system.', 'Confirm the stole dimensions, base colour, artwork placement and the way it will sit over the chosen gown before production.'],
    selection: 'Review length, width, fabric, edge finish, neck shape and colour against the ceremony dress plan. If multiple departments use different colours, provide a clear quantity split.',
    branding: 'Institute crests, course names and graduation years may be embroidered or printed depending on the selected stole and artwork. Keep text readable at ceremony and photography distance.',
    uses: ['College and university convocations', 'Coaching and training completion ceremonies', 'Department and course identification', 'Academic awards and recognition events'],
    relatedLinks: [{ href: '/stationery/graduation-degree-folders', label: 'Degree certificate folders' }, { href: '/apparel-accessories/graduation-gown', label: 'Graduation gowns' }, { href: '/contact', label: 'Request graduation-stole pricing' }],
    faqs: [
      { q: 'Can a graduation stole include a logo and course name?', a: 'Yes, suitable stoles can include approved logos, institute names, course details or graduating years.' },
      { q: 'Can different departments use different stole colours?', a: 'Yes, where the selected product and quantities support it. Provide the colour and quantity split for each department.' },
      { q: 'Should the gown be selected before the stole?', a: 'It helps to confirm both together so length, neck shape and colours work as a coordinated ceremony set.' },
      { q: 'What details are needed for a custom stole quote?', a: 'Share quantity, dimensions or selected product, colours, artwork, department split, delivery city and ceremony date.' },
    ],
  }),
  'water-bottle': focusedCategoryPage({
    category: 'promotional-items',
    title: 'Customized Water Bottles for Schools and Coaching Institutes',
    metaTitle: 'Customized Water Bottles in Bulk for Schools & Institutes',
    metaDescription: 'Customized water bottles in bulk for schools, coaching institutes and student kits. Compare capacity, material and logo branding options.',
    keywords: ['customised water bottles in bulk for schools', 'custom water bottles for coaching institutes', 'student kit bottles with logo', 'bulk branded bottles India'],
    intro: ['Customized water bottles can be planned for student kits, staff use, sports days, seminars and institute events. Select the bottle for the age group and intended use before choosing the branding treatment.', 'Capacity, material, lid design and care instructions vary by product. Review the current specification and any suitability information before placing a bulk order.'],
    selection: 'Compare capacity, bottle material, lid or sipper mechanism, dimensions and cleaning guidance. For younger students or sports use, consider carrying and handling requirements.',
    branding: 'Logo size, shape and colour count determine the workable print area and process. Curved surfaces can limit very fine text, so provide clear artwork for production review.',
    uses: ['School and coaching student kits', 'Sports days and outdoor programmes', 'Faculty and staff merchandise', 'Seminars, orientations and events'],
    relatedLinks: [{ href: '/bags/tote-bag', label: 'Student-kit tote bags' }, { href: '/stationery/notebook', label: 'Custom student notebooks' }, { href: '/contact', label: 'Request bottle pricing' }],
    faqs: [
      { q: 'Can school logos be printed on water bottles?', a: 'Yes, suitable bottles can carry an approved school or institute logo. The bottle surface and artwork determine the print process and area.' },
      { q: 'Which bottle capacity is best for students?', a: 'That depends on age group, use and carrying needs. Compare the capacity and dimensions of current products before selecting.' },
      { q: 'Can bottles be included in a complete student kit?', a: 'Yes. Share the bag and other kit items so dimensions, branding and packing can be coordinated.' },
      { q: 'What should be supplied for bulk bottle pricing?', a: 'Share product preference, capacity, quantity, logo, print requirement, delivery city and needed date.' },
    ],
  }),
};

export function getSubcategorySeoContent(category, slug) {
  const content = subcategorySeoContent[slug];
  return content && content.category === category ? content : null;
}
