const section = (heading, text, items = []) => ({ heading, text, items });
const faq = (q, a) => ({ q, a });

export const solutionPages = {
  'custom-merchandise-for-educational-institutions': {
    type: 'solution',
    title: 'Custom Merchandise for Educational Institutions',
    metaTitle: 'Custom Merchandise for Educational Institutions | CoachingPromo',
    description: 'Plan custom apparel, bags, stationery, student kits, awards and event merchandise for schools, colleges, universities and training institutes in India.',
    eyebrow: 'EDUCATION MERCHANDISE · INDIA',
    intro: 'Educational merchandise works best when every item has a clear job: identify a team, support admissions, equip a student batch, recognise achievement or extend an institution’s visual identity. CoachingPromo brings relevant product categories into one planning route for institutional bulk orders.',
    sections: [
      section('Build the range around the recipient', 'Start with the people who will receive or use the products. Students may need practical bags, notebooks and bottles; faculty and staff may need coordinated apparel; admissions and event teams may need kits, folders, lanyards or giveaways.', ['Student and orientation merchandise', 'Faculty apparel and staff uniforms', 'Admission, seminar and event requirements', 'Awards, convocation and recognition products']),
      section('Choose products that work together', 'A coordinated order uses a consistent logo, colour palette and purpose across products. Combine only items that support the programme instead of adding unrelated gifts. Existing catalogue pages show current product families; final availability and specifications are confirmed during quotation.'),
      section('Prepare a useful bulk-order brief', 'Share the audience, approximate quantity, product mix, artwork, delivery city and required date. For apparel include an expected size split; for printed stationery include format and page requirements; for kits describe packing or branch-wise distribution needs.'),
    ],
    links: [['/categories/apparel-accessories', 'Custom apparel'], ['/categories/bags', 'Bags and backpacks'], ['/categories/stationery', 'Printed stationery'], ['/solutions/student-welcome-kits', 'Student welcome kits'], ['/contact', 'Discuss an institutional order']],
    faqs: [
      faq('Which products can be customized for an educational institution?', 'The catalogue includes apparel, bags, notebooks, folders, pens, drinkware, awards and graduation products. Suitable branding and product options depend on the selected item, artwork and quantity.'),
      faq('Can one enquiry include several merchandise categories?', 'Yes. List the required products, approximate quantities and common deadline so the team can review the requirement as a coordinated institutional order.'),
      faq('How are MOQ, price and delivery confirmed?', 'They are confirmed against the current product, branding method, quantity, destination and schedule. Contact CoachingPromo for a current quotation rather than relying on a generic figure.'),
    ],
  },
  'student-welcome-kits': {
    type: 'solution', title: 'Student Welcome Kits for Institutes, Schools and Colleges',
    metaTitle: 'Student Welcome Kits for Institutes | Custom Bulk Kits',
    description: 'Plan branded student welcome, admission and orientation kits with bags, notebooks, pens, bottles, folders and ID products for institutional bulk orders.',
    eyebrow: 'ADMISSION & ORIENTATION KITS',
    intro: 'A student welcome kit should help a new learner from the first day. Build the kit around the programme, age group, distribution method and budget, then apply the institution’s branding consistently across the selected items.',
    sections: [
      section('Choose a practical kit format', 'The right combination depends on what students will actually use and what the institution already provides.', ['Notebook or notepad for class use', 'Pen and printed folder for forms or schedules', 'Bottle, tote bag or backpack for daily use', 'Lanyard and ID-card accessories where required', 'Programme information supplied by the institution']),
      section('Plan branding and packing together', 'Use one approved logo file and define placements before production. If kits are distributed by campus, branch, course or batch, share the packing labels and quantity split early. Personalized names or IDs require a final checked data sheet.'),
      section('Request a comparable quotation', 'Specify each component, quantity, preferred material or format, number of branding positions, delivery location and required date. If the budget is fixed, share it as a planning constraint; the team can suggest a simpler product mix without inventing a universal kit price.'),
    ],
    links: [['/bags/tote-bag', 'Printed tote bags'], ['/bags/institute-backpacks', 'Institute backpacks'], ['/stationery/notebook', 'Custom notebooks'], ['/stationery/customized-pens', 'Promotional pens'], ['/promotional-items/water-bottle', 'Custom bottles'], ['/stationery/lanyard-and-id-card', 'Lanyards and ID products']],
    faqs: [faq('What can be included in a student welcome kit?', 'Common components include a bag, notebook, pen, bottle, folder and lanyard. The final combination should match the programme, recipient and approved budget.'), faq('Can admission and orientation kits use different contents?', 'Yes. An admission kit may focus on documents and information, while an orientation kit may add daily-use merchandise. Contents can be planned separately.'), faq('Can kits be packed by branch or course?', 'Include the required packing and labelling split in the enquiry. Feasibility and any related cost are confirmed with the quotation.')],
  },
  'event-merchandise-for-educational-institutions': {
    type: 'solution', title: 'Event Merchandise for Educational Institutions',
    metaTitle: 'Event Merchandise for Colleges & Institutes | Bulk India',
    description: 'Plan custom merchandise for college fests, seminars, workshops, competitions and institute events, with coordinated apparel, bags, stationery and awards.',
    eyebrow: 'FESTS · SEMINARS · WORKSHOPS',
    intro: 'Event merchandise has a short deadline and several audiences: participants, organisers, speakers, volunteers and winners. A focused product plan keeps branding consistent and reduces last-minute changes.',
    sections: [section('Match products to event roles', 'Choose products by how they will be used.', ['T-shirts, polo shirts or hoodies for organisers and teams', 'Lanyards, folders, notebooks and pens for delegates', 'Tote bags or backpacks for event materials', 'Trophies, medals and badges for recognition']), section('Lock artwork and quantities early', 'Prepare the event logo, institution logo, sponsor hierarchy, print positions, size split and recipient quantities. Keep sponsor artwork legible and avoid adding unapproved marks after production approval.'), section('Plan the deadline backwards', 'Share the event date and delivery city when enquiring. Product availability, sampling, artwork approval, production, packing and transit all affect the feasible schedule; the confirmed quotation should record the agreed specification and timing.')],
    links: [['/apparel-accessories/round-neck-t-shirts', 'Event T-shirts'], ['/apparel-accessories/polo-t-shirts', 'Polo shirts'], ['/bags/tote-bag', 'Tote bags'], ['/stationery/lanyard-and-id-card', 'Lanyards'], ['/promotional-items/trophy', 'Trophies'], ['/promotional-items/medals', 'Medals']],
    faqs: [faq('Which merchandise suits a college fest?', 'Organiser apparel, lanyards, tote bags, badges and awards are common options. Select only products that support the event format and recipient group.'), faq('Can participant and organiser merchandise differ?', 'Yes. Separate the quantity and artwork brief for each group so pricing, sizing and packing can be checked accurately.'), faq('Is urgent event delivery guaranteed?', 'No universal turnaround is stated. Share the event date and destination so current feasibility can be confirmed before ordering.')],
  },
  'corporate-gifting-for-educational-institutions': {
    type: 'solution', title: 'Corporate Gifting for Educational Institutions',
    metaTitle: 'Corporate Gifting for Educational Institutions | Bulk India',
    description: 'Source useful branded gifts for faculty, teachers, speakers, partners and education teams, with bulk quotation based on product, branding and quantity.',
    eyebrow: 'INSTITUTIONAL GIFTING',
    intro: 'Institutional gifting should reflect the recipient and occasion. A useful, well-branded item is generally stronger than a large assortment with no clear purpose. This hub connects education teams with relevant gift categories without making unsupported price or delivery promises.',
    sections: [section('Plan by occasion and recipient', 'Define whether the gift is for faculty onboarding, teacher appreciation, a speaker, partner recognition, an achiever or a seasonal programme.', ['Diaries and planners for planning-led programmes', 'Bottles, mugs and desk products for everyday use', 'Bags, notebooks and pens for kits', 'Trophies, medals and folders for formal recognition']), section('Keep branding appropriate', 'Compact logo placement may suit a recognition gift, while an event kit can carry campaign artwork. Confirm the product surface, print area, colour and artwork proof before approving a bulk order.'), section('Share the quotation inputs', 'Send the occasion, recipient count, preferred products, branding artwork, delivery location and needed date. Current MOQ, stock, customization method, price and packing are confirmed for that requirement.')],
    links: [['/promotional-items/diary-set', 'Customized diaries'], ['/promotional-items/planner', 'Planners'], ['/promotional-items/mug', 'Promotional mugs'], ['/promotional-items/water-bottle', 'Branded bottles'], ['/promotional-items/trophy', 'Awards and trophies']],
    faqs: [faq('Do you publish a fixed institutional gift price?', 'No. Pricing varies with the product, quantity, branding, packing and destination. Request a current quotation for a defined requirement.'), faq('Can gifts be selected for teachers or faculty?', 'Yes. Share the occasion, recipient profile and budget range so suitable catalogue categories can be discussed.'), faq('Can several products be packed as a gift set?', 'Describe the required combination and packing in the enquiry. Feasibility is confirmed against the chosen items and quantity.')],
  },
  'eco-friendly-promotional-products': {
    type: 'solution', title: 'Eco-Friendly Promotional Products for Institutions',
    metaTitle: 'Eco-Friendly Promotional Products for Institutions | India',
    description: 'Explore reusable and lower-impact merchandise options such as jute bags, selected notebooks, pens and bottles for education-sector bulk orders.',
    eyebrow: 'REUSABLE & MATERIAL-CONSCIOUS OPTIONS',
    intro: '“Eco-friendly” is a broad claim, so product selection should be based on specific, verifiable attributes such as reusable function, material composition or recycled content supplied for the item. CoachingPromo does not treat a green colour or generic label as proof of sustainability.',
    sections: [section('Start with a specific product attribute', 'Ask what the claim means for the exact item.', ['Reusable jute or fabric bags', 'Refillable or reusable drinkware', 'Paper, bamboo or other material-specific pen options', 'Notebooks with confirmed paper or cover specifications']), section('Avoid vague environmental claims', 'Record the supplied material specification and use accurate wording in artwork or campaign copy. Do not claim compostability, recycled percentage, certification or carbon benefit unless documentation supports it.'), section('Plan durability and usefulness', 'A product that is repeatedly used may support a lower-waste programme better than a novelty item. Consider expected life, recipient need, print durability, packaging and how the institution will distribute it.')],
    links: [['/bags/jute-bag', 'Jute bags'], ['/stationery/customized-pens', 'Customized pens'], ['/stationery/notebook', 'Notebooks'], ['/promotional-items/water-bottle', 'Reusable bottles'], ['/solutions/student-welcome-kits', 'Student kits']],
    faqs: [faq('Does every item on this page carry an environmental certification?', 'No. Certifications and composition must be verified for the selected product. Ask for the current specification before making a claim.'), faq('Can eco-conscious items be combined in a student kit?', 'Yes, when the selected items meet the institution’s requirements. Confirm each product’s material and availability during quotation.'), faq('What information should an institution request?', 'Request the material composition, reusable function, available packaging and any documented certification relevant to the exact product.')],
  },
  'convocation-products': {
    type: 'solution', title: 'Convocation and Graduation Products',
    metaTitle: 'Convocation & Graduation Products | Bulk Institutional Orders',
    description: 'Coordinate graduation gowns, caps, stoles, hoods, degree folders and recognition products for college, university and institutional ceremonies.',
    eyebrow: 'GRADUATION & CONVOCATION',
    intro: 'Convocation orders involve coordinated garments, academic colours, certificate formats and ceremony deadlines. Use this hub to plan the complete requirement while keeping individual product specifications on their catalogue pages.',
    sections: [section('Build the ceremony requirement', 'List each recipient group and required product.', ['Graduation gowns and hats', 'Stoles, sashes and academic hoods', 'Degree or certificate folders', 'Medals, badges or trophies where required']), section('Confirm fit, colour and document size', 'Provide expected gown quantities and size requirements, approved academic colours, stole or hood layout, and the finished certificate dimensions for folders. Request current samples or specifications when visual matching is important.'), section('Control artwork and distribution', 'Approve crests, text and colour references before production. Share packing requirements by course, faculty, campus or recipient group and allow time for checking quantities before the ceremony.')],
    links: [['/apparel-accessories/graduation-gown', 'Graduation gowns'], ['/apparel-accessories/graduation-hat', 'Graduation hats'], ['/apparel-accessories/graduation-stole', 'Stoles and sashes'], ['/apparel-accessories/graduation-hood', 'Graduation hoods'], ['/stationery/graduation-degree-folders', 'Degree folders']],
    faqs: [faq('Can graduation products be ordered as one coordinated requirement?', 'Yes. List the gown, cap, stole, hood, folder and award quantities needed so specifications and availability can be reviewed together.'), faq('How should degree-folder size be specified?', 'Share the finished certificate dimensions, orientation and any insert or holding method required. The current folder specification is confirmed before ordering.'), faq('Is a fixed ceremony turnaround available?', 'Turnaround depends on products, quantity, customization, approvals and destination. Confirm the schedule for the specific ceremony before placing the order.')],
  },
};

export const industryPages = {
  schools: {
    type: 'industry', title: 'Custom School Merchandise and Promotional Products', metaTitle: 'Custom School Merchandise & Promotional Products | India',
    description: 'Plan branded apparel, student kits, notebooks, bags, bottles, awards and admission merchandise for schools in India.', eyebrow: 'FOR SCHOOLS',
    intro: 'School merchandise should be age-appropriate, useful and consistent with the school’s approved identity. The strongest programmes separate daily student items, staff requirements, admissions, events and recognition instead of using one product for every purpose.',
    sections: [section('Merchandise for school programmes', 'Plan each requirement around its users.', ['Student bags, notebooks, bottles and ID accessories', 'Teacher and staff apparel', 'Admission or orientation kits', 'House, sports and event merchandise', 'Awards and recognition products']), section('Provide product and safeguarding details', 'Share recipient age group, quantity, required sizes, logo artwork, school colours and delivery location. Avoid adding student names or other personal data unless it is necessary, approved and supplied through a controlled final list.'), section('Confirm facts before communicating to families', 'Material, size, care, price, availability and delivery should be confirmed for the selected item before the school announces it. Current commercial terms are supplied in the quotation.')],
    links: [['/solutions/student-welcome-kits', 'School welcome kits'], ['/categories/bags', 'School bags'], ['/stationery/notebook', 'School notebooks'], ['/promotional-items/water-bottle', 'School bottles'], ['/promotional-items/trophy', 'Awards and trophies']],
    faqs: [faq('Which products are suitable for school branding?', 'Common categories include bags, notebooks, bottles, apparel, ID accessories and awards. Suitability depends on age group, use and school policy.'), faq('Can staff and student requirements be quoted together?', 'Yes. Separate the product, size and quantity details for each recipient group in the enquiry.'), faq('Are product specifications fixed across all orders?', 'No. Confirm current materials, sizes, branding methods, MOQ and availability for the selected item.')],
  },
  'colleges-universities': {
    type: 'industry', title: 'College and University Merchandise', metaTitle: 'College & University Merchandise | Custom Bulk Orders India',
    description: 'Custom merchandise for college and university students, societies, fests, orientation, alumni programmes and convocation events.', eyebrow: 'FOR COLLEGES & UNIVERSITIES',
    intro: 'Higher-education merchandise can serve departments, student societies, festivals, orientation programmes, alumni activity, sports teams and graduation. Each use case needs a distinct brief even when the same institution logo appears across the range.',
    sections: [section('Plan by campus use case', 'Separate everyday and event requirements.', ['Batch T-shirts, hoodies and jackets', 'Society, club and college-fest merchandise', 'Orientation and welcome kits', 'Department bags, notebooks and drinkware', 'Convocation wear, folders and awards']), section('Manage multiple identities', 'Provide approved institution, department, society, event and sponsor artwork with a clear hierarchy. Confirm who can approve the final mockup and collect personalization in one checked sheet.'), section('Coordinate quantities and delivery', 'Share size splits, programme dates, campus or hostel delivery requirements and packing groups. Pricing and timing depend on the chosen product, branding and confirmed quantity.')],
    links: [['/custom-hoodies-for-coaching-institutes', 'Custom hoodies'], ['/apparel-accessories/round-neck-t-shirts', 'College T-shirts'], ['/solutions/event-merchandise-for-educational-institutions', 'Fest merchandise'], ['/solutions/student-welcome-kits', 'Orientation kits'], ['/solutions/convocation-products', 'Convocation products']],
    faqs: [faq('Can student societies order merchandise with their artwork?', 'Yes, subject to approved artwork and the selected product’s branding area. Share both the institution and society requirements in the brief.'), faq('Can names or batch years be personalized?', 'Personalization may be possible on suitable products. Provide the final checked data and confirm the method, placement and cost before production.'), faq('Can convocation and fest products be ordered together?', 'They can be included in one enquiry, but each product group should retain its own quantities, specifications and deadline.')],
  },
  'training-institutes': {
    type: 'industry', title: 'Merchandise for Training Institutes and Academies', metaTitle: 'Training Institute & Academy Merchandise | Bulk India',
    description: 'Branded merchandise and training kits for academies, skill centres, vocational programmes, workshops and corporate training teams.', eyebrow: 'FOR TRAINING CENTRES & ACADEMIES',
    intro: 'Training merchandise should support the programme rather than distract from it. Build a practical kit for learners, a clear identity for trainers and staff, or a focused set of materials for workshops and seminars.',
    sections: [section('Products for training delivery', 'Match the item to the programme.', ['Notebooks, pens and folders for course material', 'Bags and bottles for learner kits', 'Polo shirts, T-shirts or jackets for trainers and staff', 'Lanyards and ID accessories for cohorts and events']), section('Account for course length and format', 'A one-day workshop may need a compact stationery kit; a longer programme may justify a durable bag, bottle or apparel. Share the learning format, cohort size, delivery city and schedule.'), section('Keep programme branding consistent', 'Use approved academy or sponsor artwork across selected products and define which items need participant names, course titles or batch identifiers. Confirm every personalization list before production.')],
    links: [['/stationery/notebook', 'Training notebooks'], ['/stationery/branding-files-and-folders', 'Course folders'], ['/bags/institute-backpacks', 'Training bags'], ['/apparel-accessories/polo-t-shirts', 'Trainer polo shirts'], ['/solutions/student-welcome-kits', 'Training kits']],
    faqs: [faq('What can a customized training kit contain?', 'A kit can combine a notebook, pen, folder, bag, bottle or ID accessory according to the programme and budget.'), faq('Can kits be labelled by course or cohort?', 'Describe the labelling and packing split in the enquiry. Feasibility is confirmed for the selected products and quantity.'), faq('Do you state a universal minimum order?', 'No. MOQ varies by product and customization, so it is confirmed with the current quotation.')],
  },
};

export const guidePages = {
  'promotional-product-planning-for-coaching-institutes': {
    type: 'guide', title: 'How to Plan Promotional Products for a Coaching Institute', metaTitle: 'Promotional Product Ideas for Coaching Institutes | Guide',
    description: 'A practical framework for choosing useful coaching institute merchandise for admissions, student batches, staff, seminars and recognition.', eyebrow: 'PLANNING GUIDE',
    intro: 'The best promotional product is the one that supports a real institute activity. Begin with the recipient and distribution moment, then select a product, specification and branding method that fits the available budget and time.',
    sections: [section('Map products to the programme', 'Admissions may need folders or compact welcome kits; classroom use may favour notebooks and bottles; staff identity may need apparel; seminars may need lanyards and stationery; achiever programmes may need awards.'), section('Prioritise usefulness over quantity', 'A smaller set of relevant products is easier to specify, brand and distribute. Check that each item will be used after the campaign and that it fits the institution’s visual identity.'), section('Write a complete enquiry brief', 'Include purpose, recipients, approximate quantity, artwork, product preferences, delivery city and deadline. Ask the supplier to confirm material, dimensions, branding, MOQ, packing, taxes and delivery rather than assuming them.')],
    links: [['/', 'Promotional products for coaching institutes'], ['/solutions/student-welcome-kits', 'Student welcome kits'], ['/solutions/event-merchandise-for-educational-institutions', 'Event merchandise'], ['/contact', 'Request a quotation']],
    faqs: [faq('Which product should a coaching institute start with?', 'Start with the immediate programme and recipient. A daily-use student item, staff apparel or a focused admission kit is usually easier to justify than unrelated giveaways.'), faq('Should every item carry a large logo?', 'No. Branding size should suit the product and recipient. A compact, legible mark often creates a more usable item.'), faq('How should products be compared?', 'Compare the same specification, branding area, quantity, tax, packing and delivery assumptions across quotations.')],
  },
  'student-welcome-kit-checklist': {
    type: 'guide', title: 'Student Welcome Kit Checklist', metaTitle: 'What to Include in a Student Welcome Kit | Checklist',
    description: 'Use this checklist to plan useful admission and orientation kits for coaching institutes, schools, colleges and training programmes.', eyebrow: 'KIT CHECKLIST',
    intro: 'A useful welcome kit answers three questions: what the student needs on day one, what information the institution must provide, and how the items will be distributed. The final contents should follow those answers.',
    sections: [section('Essential learning items', 'Consider a notebook or notepad, pen and printed folder. Confirm formats, page counts, paper or cover requirements and the documents the institution will insert.'), section('Daily-use additions', 'A tote bag, backpack, bottle or lanyard can add practical value when it fits the programme. Avoid including products only to increase the item count.'), section('Packing and data checklist', 'Confirm total quantity, branch or course splits, branding artwork, item colours, any names or IDs, pack sequence, delivery address and deadline. Keep a final approved spreadsheet for personalization.')],
    links: [['/solutions/student-welcome-kits', 'Order student welcome kits'], ['/stationery/notebook', 'Custom notebooks'], ['/bags/tote-bag', 'Tote bags'], ['/promotional-items/water-bottle', 'Water bottles']],
    faqs: [faq('How many items should a welcome kit contain?', 'There is no required number. Include the smallest set that is useful for the programme and fits the approved budget.'), faq('What is the difference between an admission and orientation kit?', 'Admission kits often focus on documents and initial information; orientation kits may include items used during induction or classes.'), faq('Should personalized data be sent early?', 'Collect it early, but send one final checked version for production to reduce spelling and allocation errors.')],
  },
  'college-merchandise-ideas': {
    type: 'guide', title: 'College Merchandise Ideas by Campus Use Case', metaTitle: 'College Merchandise Ideas for Fests, Clubs & Students',
    description: 'Ideas for useful college merchandise across student batches, clubs, fests, orientation, alumni programmes and graduation.', eyebrow: 'COLLEGE MERCHANDISE GUIDE',
    intro: 'College merchandise is most effective when it marks a genuine community or moment. Design for the batch, society or programme first, then choose products students will continue to use.',
    sections: [section('Batches and departments', 'T-shirts, hoodies, notebooks and bottles can carry a department, course or batch identity. Keep the college crest in its approved form and use a separate area for batch artwork.'), section('Fests, clubs and societies', 'Organiser apparel, lanyards, tote bags and badges help distinguish roles. Awards can support competitions, while notebooks or folders suit academic events.'), section('Orientation, alumni and graduation', 'Welcome kits support new students; restrained apparel or useful gifts can serve alumni activity; gowns, stoles, folders and awards support convocation.')],
    links: [['/industries/colleges-universities', 'College merchandise'], ['/solutions/event-merchandise-for-educational-institutions', 'College fest merchandise'], ['/solutions/student-welcome-kits', 'Orientation kits'], ['/solutions/convocation-products', 'Graduation products']],
    faqs: [faq('Which college merchandise works beyond a single event?', 'Useful apparel, bags, notebooks and drinkware are more likely to remain in use when the design is wearable and the product suits students.'), faq('How can sponsor logos be handled?', 'Create and approve a clear logo hierarchy, minimum sizes and placements before production.'), faq('Can products be split by club or department?', 'Yes. Provide separate quantities, artwork and packing labels for each group.')],
  },
  'custom-t-shirt-printing-guide': {
    type: 'guide', title: 'Custom T-Shirt Printing Guide for Institutions', metaTitle: 'Custom T-Shirt Printing Methods & Fabric Guide | India',
    description: 'Compare institutional T-shirt styles, fabric considerations, screen printing, DTF, heat transfer and embroidery before a bulk order.', eyebrow: 'APPAREL BUYING GUIDE',
    intro: 'A good institutional T-shirt specification combines garment style, fabric, fit, colour, artwork and printing. Price comparisons are meaningful only when those inputs match.',
    sections: [section('Choose the garment for the wearer', 'Round-neck T-shirts suit student batches, sports and events; polo shirts provide a collared staff or faculty option. Ask for the current composition, GSM, size chart and colour availability for the selected garment.'), section('Match branding to artwork', 'Screen printing can suit bold repeat designs; DTF or heat transfer can support detailed multi-colour graphics; embroidery may suit compact polo-shirt crests. Suitability depends on fabric, artwork, placement and quantity.'), section('Approve fit and artwork', 'Collect a size split from the supplier measurement chart, review a placement mockup and confirm print dimensions and colours. For complex or high-volume orders, discuss an appropriate sample or production reference.')],
    links: [['/apparel-accessories/round-neck-t-shirts', 'Custom round-neck T-shirts'], ['/apparel-accessories/polo-t-shirts', 'Custom polo T-shirts'], ['/contact', 'Request a T-shirt quotation']],
    faqs: [faq('Which fabric is best for institute T-shirts?', 'The choice depends on climate, use, care and budget. Confirm the current cotton, blend or performance options and compare samples or specifications.'), faq('Is screen printing always cheaper?', 'Not always. Cost depends on quantity, artwork size, colour count, garment and setup. Compare methods against the same brief.'), faq('Are polo shirts better for staff uniforms?', 'Polos can provide a more structured collared appearance, while round-neck shirts may suit casual or event use. The institution’s dress code should guide the choice.')],
  },
  'notebook-printing-guide': {
    type: 'guide', title: 'Custom Notebook Printing Guide for Institutes', metaTitle: 'Custom Notebook Printing Cost & Binding Guide | India',
    description: 'Plan custom notebooks by size, binding, page count, paper, cover, printing, quantity and delivery requirements.', eyebrow: 'STATIONERY BUYING GUIDE',
    intro: 'Notebook pricing cannot be compared from the cover alone. Size, page count, paper, ruling, binding, cover construction, print coverage and quantity all change the specification.',
    sections: [section('Choose format and binding', 'Spiral binding can open flat and suits active note-taking; hardbound formats provide a structured presentation; other available formats may suit budget or distribution needs. Confirm the exact current construction.'), section('Specify the inside pages', 'State finished size, page count, paper, ruling or grid, number of printed colours and whether institute information or schedules are included. Supply final proofread content for any custom inner pages.'), section('Compare complete quotations', 'Use the same dimensions, pages, materials, cover print, finishing, quantity, packing, tax and delivery location when comparing notebook printing cost.')],
    links: [['/stationery/notebook', 'Custom notebooks'], ['/stationery/notepad', 'Custom notepads'], ['/stationery/attendance-registers', 'Attendance registers'], ['/contact', 'Request a stationery quote']],
    faqs: [faq('Is spiral or hardbound better?', 'Spiral suits flat opening and frequent use; hardbound can provide a more structured finish. The best option depends on use and budget.'), faq('What affects customized notebook printing cost?', 'Size, page count, paper, binding, cover, colours, finishing, quantity, packing and delivery all affect cost.'), faq('Can institute pages be printed inside?', 'Describe the number and position of custom pages and provide final artwork. Feasibility is confirmed with the specification.')],
  },
  'admission-and-orientation-merchandise-ideas': {
    type: 'guide', title: 'Admission and Orientation Merchandise Ideas', metaTitle: 'Admission & Orientation Merchandise Ideas for Institutes',
    description: 'Plan merchandise for admissions, induction, orientation, seminars and educational events without overloading the kit.', eyebrow: 'ADMISSIONS GUIDE',
    intro: 'Admission merchandise should help the prospective or new student understand, carry or use something connected to the institution. Orientation merchandise should support the first days of the programme.',
    sections: [section('Admissions', 'Folders, pens, compact information packs and practical branded items can support counselling or enrolment when they are relevant to the process.'), section('Orientation and induction', 'A notebook, bag, bottle, lanyard or apparel item can support course induction. Choose contents around the timetable, campus and distribution format.'), section('Seminars and workshops', 'Delegate stationery, folders, lanyards and organiser apparel can make roles clear. Keep the event date, artwork approvals and packing plan visible in the ordering schedule.')],
    links: [['/solutions/student-welcome-kits', 'Admission and welcome kits'], ['/solutions/event-merchandise-for-educational-institutions', 'Event merchandise'], ['/stationery/branding-files-and-folders', 'Printed folders'], ['/contact', 'Discuss an admission campaign']],
    faqs: [faq('Should admission gifts be expensive?', 'Not necessarily. Relevance, presentation and accurate information matter more than adding costly products without a clear use.'), faq('Can seminar items be added to orientation kits?', 'Yes, if they support the programme. Keep quantities and recipient groups clear.'), faq('When should the order brief be prepared?', 'Prepare it before announcing distribution, with enough time for product confirmation, artwork approval, production and transit.')],
  },
  'how-branded-merchandise-supports-institute-branding': {
    type: 'guide', title: 'How Branded Merchandise Supports Institute Branding', metaTitle: 'How Merchandise Supports School & Institute Branding',
    description: 'Understand how consistent, useful merchandise can support recognition, belonging and programme delivery for education brands.', eyebrow: 'BRANDING GUIDE',
    intro: 'Merchandise is one physical expression of an institution’s identity. It cannot replace teaching quality or communication, but it can make teams and programmes easier to recognise when the products are useful and consistently designed.',
    sections: [section('Create consistent recognition', 'Approved logos, colours and typography across staff apparel, student items and event materials help recipients connect each touchpoint to the same institution.'), section('Support belonging and roles', 'Batch apparel, society merchandise, staff uniforms and event lanyards can identify a group or role. The design should remain appropriate for use after the event where possible.'), section('Protect the identity system', 'Use current artwork files, define clear space and colours, and nominate an approver. Avoid stretching logos, adding unapproved effects or placing small text where the production method cannot reproduce it.')],
    links: [['/', 'Coaching institute merchandise'], ['/solutions/custom-merchandise-for-educational-institutions', 'Educational merchandise'], ['/guides/custom-merchandise-branding-methods', 'Branding methods'], ['/contact', 'Discuss an institute requirement']],
    faqs: [faq('Does merchandise guarantee brand growth?', 'No. It can support recognition and programme experience, but outcomes depend on the wider institution and campaign.'), faq('Should every product use the same artwork size?', 'No. Keep the identity consistent while adapting placement and size to each product surface.'), faq('Who should approve artwork?', 'The institution should nominate an authorised approver and retain the final approved mockup or proof.')],
  },
  'custom-merchandise-branding-methods': {
    type: 'guide', title: 'Custom Merchandise Branding Methods', metaTitle: 'Logo Printing, Embroidery, DTF & Heat Transfer Guide',
    description: 'Compare common logo branding methods for institutional apparel, bags, stationery and promotional products.', eyebrow: 'CUSTOMIZATION GUIDE',
    intro: 'No branding method is best for every product. The artwork, substrate, quantity, placement, expected wear and desired appearance determine the appropriate process.',
    sections: [section('Screen printing', 'Screen printing can suit bold repeat designs on compatible garments and bags. Colour count, print area, fabric and order quantity affect the setup and result.'), section('Embroidery', 'Embroidery gives compact crests and text a stitched finish on suitable polos, hoodies, jackets and caps. Fine detail, gradients and very large areas may need artwork changes.'), section('DTF and heat transfer', 'Transfer methods can reproduce detailed or multi-colour graphics on compatible fabrics. Confirm hand feel, stretch, care and surface suitability for the selected garment.'), section('Product-specific printing', 'Pens, bottles, mugs, folders and awards use processes suited to their shape and material. Ask for the current print area and proof rather than assuming an apparel method applies.')],
    links: [['/apparel-accessories/round-neck-t-shirts', 'Printed T-shirts'], ['/custom-hoodies-for-coaching-institutes', 'Printed and embroidered hoodies'], ['/stationery/customized-pens', 'Customized pens'], ['/contact', 'Review your artwork']],
    faqs: [faq('Is embroidery always more durable than printing?', 'Durability depends on the garment, method, setup and care. Select the method for the exact product and artwork.'), faq('Which method is best for a multi-colour logo?', 'A transfer or suitable product-specific process may reproduce detail, but fabric, placement and quantity still need review.'), faq('What artwork file should be supplied?', 'Send the highest-quality vector or original file available, plus brand colours and placement instructions. The production team can confirm usable formats.')],
  },
};

export const allSeoPages = { ...solutionPages, ...industryPages, ...guidePages };
export const seoPageEntries = [
  ...Object.entries(solutionPages).map(([slug, page]) => ({ slug, path: `/solutions/${slug}`, ...page })),
  ...Object.entries(industryPages).map(([slug, page]) => ({ slug, path: `/industries/${slug}`, ...page })),
  ...Object.entries(guidePages).map(([slug, page]) => ({ slug, path: `/guides/${slug}`, ...page })),
];
